export function mountAppShell(app: HTMLDivElement): void {
  app.innerHTML = `
  <main class="escape-app">
    <section class="range-shell">
      <div class="range" aria-label="Escape parking environment">
      <section class="start-screen is-visible" aria-label="Start Escape">
        <canvas id="matryoshka-preview-canvas" aria-label="Rotating Matryoshka preview"></canvas>
        <div class="start-screen-content"><h1>ESCAPE</h1><button class="start-play-button" id="start-play-button" type="button">PLAY</button></div>
      </section>
      <section class="loading-screen" aria-live="polite" aria-label="Loading Escape">
        <div class="loading-panel">
          <span class="loading-kicker">LOADING</span>
          <h2 id="loading-title">PREPARING ESCAPE</h2>
          <div class="loading-bar"><span id="loading-bar-fill"></span></div>
          <p id="loading-status">LOADING OBJECTS...</p>
        </div>
      </section>
      <section class="episode-screen" aria-label="Episode selection">
        <div class="episode-screen-content"><p>EPISODE SELECT</p><h1>ESCAPE</h1><div class="episode-card-grid"><div class="episode-card-shell"><button class="episode-card" id="parking-lot-episode-button" type="button"><canvas class="episode-card-preview" id="parking-preview-canvas" aria-label="Parking lot 3D preview"></canvas></button><strong>PARKING LOT</strong></div><div class="episode-card-shell"><button class="episode-card" id="classroom-episode-button" type="button"><canvas class="episode-card-preview" id="classroom-preview-canvas" aria-label="Classroom 3D preview"></canvas></button><strong>CLASSROOM</strong></div><div class="episode-card-shell"><button class="episode-card" id="chess-episode-button" type="button"><canvas class="episode-card-preview" id="chess-preview-canvas" aria-label="Chess 3D preview"></canvas></button><strong>CHESS</strong></div></div></div>
      </section>
      <canvas id="range-canvas" aria-label="Escape game view"></canvas>
      <div class="crosshair" aria-hidden="true"><span></span><i></i><b></b><em></em></div>
      <div class="hit-marker" aria-hidden="true"><i></i><i></i><i></i><i></i></div>
      <div class="fear-overlay" aria-hidden="true"></div>
      <div class="death-overlay" aria-hidden="true"></div>
      <section class="death-screen" aria-label="You died">
        <div class="death-actions"><button class="death-action-button" id="death-retry-button" type="button">RETRY</button><button class="death-action-button" id="death-exit-button" type="button">EXIT</button></div>
      </section>
      <div class="episode-fade-overlay" aria-hidden="true"></div>
      <button class="settings-button" type="button" aria-label="Open settings" title="Open settings">⚙</button>
      <button class="fullscreen-button" type="button" aria-label="Enter fullscreen" title="Enter fullscreen">⛶</button>
      <div class="settings-overlay" aria-hidden="true">
        <button class="settings-close" type="button" aria-label="Close settings" title="Close settings">×</button>
        <section class="menu-home menu-view is-visible" aria-label="Pause menu">
          <h1>PAUSED</h1>
          <div class="menu-choice-list"><button class="menu-choice-button" id="menu-settings-button" type="button"><strong>ENVIRONMENT SETTINGS</strong><span>Adjust your escape environment</span></button><button class="menu-choice-button menu-exit-button" id="menu-exit-button" type="button"><strong>EXIT</strong><span>Return to menu</span></button></div>
        </section>
        <section class="mode-menu menu-view" aria-label="Mode selection">
          <h1>MODE SELECT</h1>
          <div class="mode-layout">
            <nav class="mode-category-nav" aria-label="Mode categories"><button class="mode-category-button is-active" data-mode-category="flicking" type="button">FLICKING</button><button class="mode-category-button" data-mode-category="tracking" type="button">TRACKING</button></nav>
            <div class="mode-category-content"><section class="mode-panel is-visible" data-mode-panel="flicking"><h2>FLICKING</h2><div class="mode-select" role="group" aria-label="Flicking modes"><button class="mode-button is-active" data-mode="flickshot" type="button">FLICKSHOT</button><button class="mode-button" data-mode="microshot" type="button">MICROSHOT</button><button class="mode-button" data-mode="gridshot" type="button">GRIDSHOT</button><button class="mode-button" data-mode="reflexshot" type="button">REFLEXSHOT</button></div></section><section class="mode-panel" data-mode-panel="tracking"><h2>TRACKING</h2><div class="mode-select" role="group" aria-label="Tracking modes"><button class="mode-button" data-mode="strafetrack" type="button">STRAFETRACK</button><button class="mode-button" data-mode="spheretrack" type="button">SPHERETRACK</button><button class="mode-button" data-mode="fallingtrack" type="button">FALLING TRACK</button></div></section></div>
          </div>
        </section>
        <div class="settings-content">
          <div class="settings-heading"><span>ENVIRONMENT SETTINGS</span></div>
          <div class="settings-layout">
            <nav class="settings-nav" aria-label="Settings categories"><button class="settings-category is-active" data-category="display" type="button">DISPLAY &amp; GRAPHICS</button><button class="settings-category" data-category="weapon" type="button">WEAPON &amp; BALLISTICS</button><button class="settings-category" data-category="controls" type="button">MOUSE &amp; CONTROLS</button><button class="settings-category" data-category="crosshair" type="button">CROSSHAIR</button><button class="settings-category" data-category="targets" type="button">TARGETS &amp; ENVIRONMENT</button><button class="settings-category" data-category="sound" type="button">SOUND</button></nav>
            <div class="settings-category-content">
              <section class="settings-group settings-panel-group is-visible" data-category-panel="display"><h2>DISPLAY &amp; GRAPHICS</h2><label>RENDER DISTANCE <output id="render-distance-value">600</output><input id="render-distance-setting" type="range" min="100" max="600" step="10" value="600"></label><label>FOV <output id="fov-value">65</output><input id="fov-setting" type="range" min="45" max="103" step="1" value="65"></label><label>RESOLUTION SCALE <output id="resolution-scale-value">100%</output><input id="resolution-scale-setting" type="range" min="50" max="150" step="5" value="100"></label><label>MAX FPS <select id="max-fps-setting"><option value="0">UNLIMITED</option><option value="60">60</option><option value="144">144</option><option value="240">240</option></select></label><label class="toggle-row">ANTI-ALIASING <input id="antialiasing-setting" type="checkbox" checked></label></section>
              <section class="settings-group settings-panel-group" data-category-panel="weapon"><h2>WEAPON &amp; BALLISTICS</h2><div class="weapon-preview"><h2>CURRENT WEAPON</h2><canvas id="weapon-preview-canvas" aria-label="Current weapon preview"></canvas><strong id="current-weapon-name">COLT 1911</strong></div><label>WEAPON <select id="weapon-setting"><option value="pistol">PISTOL</option></select></label><label>BULLET SPEED <output id="bullet-speed-value">253</output><input id="bullet-speed-setting" type="range" min="50" max="500" step="1" value="253"></label><label>RECOIL <output id="recoil-value">50%</output><input id="recoil-setting" type="range" min="0" max="100" value="50"></label><label>SPREAD <output id="spread-value">50%</output><input id="spread-setting" type="range" min="0" max="150" value="50"></label><label>MOVEMENT SPREAD <output id="movement-spread-value">225%</output><input id="movement-spread-setting" type="range" min="100" max="500" value="225"></label><label>AIM JUMP SPREAD <output id="aiming-jump-spread-value">550%</output><input id="aiming-jump-spread-setting" type="range" min="100" max="800" value="550"></label><label>HIPFIRE JUMP SPREAD <output id="hipfire-jump-spread-value">450%</output><input id="hipfire-jump-spread-setting" type="range" min="100" max="800" value="450"></label><label>BULLET DROP <output id="bullet-drop-value">100%</output><input id="bullet-drop-setting" type="range" min="0" max="200" value="100"></label></section>
              <section class="settings-group settings-panel-group" data-category-panel="controls"><h2>MOUSE &amp; CONTROLS</h2><label>SENSITIVITY <output id="settings-sensitivity-value">0.70</output><input id="settings-sensitivity" type="range" min="0.2" max="1.5" step="0.05" value="0.7"></label><label>DPI MULTIPLIER <output id="dpi-value">800</output><input id="dpi-setting" type="range" min="100" max="3200" step="100" value="800"></label><label>ADS RATIO <output id="ads-ratio-value">1.00</output><input id="ads-ratio-setting" type="range" min="0.1" max="2" step="0.05" value="1"></label><label>ADS FOV <output id="ads-fov-value">48</output><input id="ads-fov-setting" type="range" min="30" max="65" step="1" value="48"></label><label class="toggle-row">RAW INPUT <input id="raw-input-setting" type="checkbox" checked></label></section>
              <section class="settings-group settings-panel-group" data-category-panel="crosshair"><h2>CROSSHAIR</h2><label>STYLE <select id="crosshair-style-setting"><option>DOT + CROSS</option><option>DOT</option><option>CROSS</option><option>CIRCLE</option></select></label><label>COLOR <input id="crosshair-color-setting" type="color" value="#ffffff"></label><label>GAP <output id="crosshair-gap-value">14px</output><input id="crosshair-gap-setting" type="range" min="0" max="30" value="14"></label><label>LENGTH <output id="crosshair-length-value">8px</output><input id="crosshair-length-setting" type="range" min="2" max="24" value="8"></label><label>THICKNESS <output id="crosshair-thickness-value">1px</output><input id="crosshair-thickness-setting" type="range" min="1" max="5" value="1"></label><label>DOT SIZE <output id="crosshair-dot-size-value">5px</output><input id="crosshair-dot-size-setting" type="range" min="1" max="12" value="5"></label><label>CIRCLE SIZE <output id="crosshair-circle-size-value">30px</output><input id="crosshair-circle-size-setting" type="range" min="8" max="58" value="30"></label><label>OPACITY <output id="crosshair-opacity-value">90%</output><input id="crosshair-opacity-setting" type="range" min="10" max="100" value="90"></label><label>OUTLINE COLOR <input id="crosshair-outline-color-setting" type="color" value="#000000"></label><label>OUTLINE THICKNESS <output id="crosshair-outline-thickness-value">0px</output><input id="crosshair-outline-thickness-setting" type="range" min="0" max="4" value="0"></label><label class="toggle-row">DYNAMIC RESPONSE <input id="crosshair-dynamic-setting" type="checkbox" checked></label><label>DYNAMIC STRENGTH <output id="crosshair-dynamic-strength-value">100%</output><input id="crosshair-dynamic-strength-setting" type="range" min="0" max="200" value="100"></label><h2>HIT MARKER</h2><label>COLOR <input id="hit-marker-color-setting" type="color" value="#67d68b"></label><label>SIZE <output id="hit-marker-size-value">36px</output><input id="hit-marker-size-setting" type="range" min="16" max="72" value="36"></label><label>LENGTH <output id="hit-marker-length-value">9px</output><input id="hit-marker-length-setting" type="range" min="3" max="24" value="9"></label><label>THICKNESS <output id="hit-marker-thickness-value">1px</output><input id="hit-marker-thickness-setting" type="range" min="1" max="5" value="1"></label><label>GAP <output id="hit-marker-gap-value">10px</output><input id="hit-marker-gap-setting" type="range" min="4" max="24" value="10"></label><label>FADE TIME <output id="hit-marker-duration-value">0.22s</output><input id="hit-marker-duration-setting" type="range" min="0.05" max="1" step="0.01" value="0.22"></label></section>
              <section class="settings-group settings-panel-group" data-category-panel="targets"><h2>TARGETS &amp; ENVIRONMENT</h2><label>BACKGROUND <input id="background-color-setting" type="color" value="#0b0e12"></label><label>FLOOR <input id="floor-color-setting" type="color" value="#171d24"></label><label>GRID <input id="grid-color-setting" type="color" value="#33404a"></label><label>TARGET <input id="target-color-setting" type="color" value="#e33f32"></label><label>TARGET SIZE <output id="target-size-value">100%</output><input id="target-size-setting" type="range" min="50" max="150" value="100"></label><label>TRACKING SPEED <output id="tracking-speed-value">4.0</output><input id="tracking-speed-setting" type="range" min="1" max="10" step="0.5" value="4"></label><label>FALLING HORIZONTAL FORCE <output id="falling-horizontal-force-value">3.4</output><input id="falling-horizontal-force-setting" type="range" min="0" max="8" step="0.1" value="3.4"></label><label>FALLING LAUNCH <output id="falling-launch-value">12.0</output><input id="falling-launch-setting" type="range" min="0" max="20" step="0.5" value="12"></label><label>FALLING GRAVITY <output id="falling-gravity-value">18.0</output><input id="falling-gravity-setting" type="range" min="1" max="36" step="0.5" value="18"></label><label>FALLING RESPAWN DELAY <output id="falling-respawn-delay-value">0.60s</output><input id="falling-respawn-delay-setting" type="range" min="0.1" max="2" step="0.05" value="0.6"></label></section>
              <section class="settings-group settings-panel-group" data-category-panel="sound"><h2>SOUND</h2><label>MASTER VOLUME <output id="master-volume-value">100%</output><input id="master-volume-setting" type="range" min="0" max="100" value="100"></label></section>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section>
  </main>
`;
}
